### ISSUE TITLE
Dreiecksnetz für skalare Felder

### ISSUE THREAD

**Issue by BenSaero** [VRLAB-HSKL/Vektoranalysis#12]
Zur Darstellung von skalaren Feldern werden wir ein eigenes Netz aus Dreiecken verwenden. Dieses muss in das Projekt eingebunden und getestet werden.

**Comment by MBrill** [comment]
In MBU gibt es eine Basisklasse für polygonale Netze, die auch schon für den Airplane verwendet wird. Die sollten wir hier einsetzen

**Comment by BenSaero** [comment]
Für die skalaren Felder wird nun ein Dreiecksnetz generiert und in der Applikation angezeigt, mit eigener Dreiecks-, Index- und Normalenberechnung. Sie können einseitig oder beidseitig generiert werden (backfaces). Diese Netze werden mithilfe von uv-Koordinaten mit Texturen texturiert. Diese Texturen werden durch plotly aus Python heraus generiert und exportiert.
