### ISSUE TITLE
Tischmodell und UI-Elemente

### ISSUE THREAD

**Issue by MBrill** [VRLAB-HSKL/Vektoranalysis#16]
Für die Visualisierung von ebenen Kurven, skalaren Feldern, Graphen und anderen 2D Konstruktionen verwenden wir einen "Tisch", der die xy-Ebene darstellt. Wir versehen den tisch mit einigen UI-elementen wie play, stop usw.

Wir verwenden im ersten Schritt den "Tisch" aus dem Projekt von Marco Noll.

**Comment by BenSaero** [comment]
In die Szene wurde der Tisch aus dem Projekt von Marco Noll eingebunden und mit verschiedenen Buttons versehen. Diese Buttons dienen aktuell der Auswahl der Ansicht auf Display Kurven, das Navigieren zwischen einzelnen Display Kurven, so wie dem Steuern der Spurabfahrt
