### ISSUE TITLE
Einbinden eines Modellflugzeug als Kurvenfahrzeug in die Szene

### ISSUE THREAD

**Issue by BenSaero** [VRLAB-HSKL/Vektoranalysis#9]
Anstatt des aktuellen Placeholders soll ein modelliertes Flugzeug ausprobiert und bei erfolgreichem Test eingesetzt werden. Hierzu liegt bereits ein Modell vor.

**Comment by MBrill** [comment]
obj ist fertig und ich habe es testhalber in unity importiert. Ging auch, allerdings müssen die Durchlaufrichtungen für die Facetten geändert werden, da Unity ja ein linkshändiges Koordinatensystem verwendet. Das könnte man mit einem shader lösen, der beide Seite rendert (Unity macht automatisch backface culling, das heißt Facetten von denen wir die Rückseite sehen werden ausgeblendet.

Ich mache eine neue Version, sobald das getestet ist lege ich das obj oder fbx dann ins repo!

**Comment by MBrill** [comment]
Erste Version findet man im repo vrkl, in den Beispielen für Netze. Modell ist vermutlich noch zu groß, aber man kann es schon gleichmüssig skalieren in den transforms.

**Comment by BenSaero** [comment]
Das Modell befindet sich nun in der Szene. Es folgt den entsprechenden Parameterkurven und rotiert basierend auf den Moving Frames. Zukünfigt sollte der lokale Import entfernt und durch eine Dependency auf das MBU Package ersetzt werden.
